# Generated by Django 4.2 on 2023-04-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0009_showbairro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='showBairro',
        ),
        migrations.AlterModelOptions(
            name='bairro',
            options={'ordering': ['nome']},
        ),
    ]
